[control_nodes]
k8_master ansible_host=127.0.0.1 ansible_port=2601


[worker_nodes]
k8_worker_1 ansible_host=127.0.0.1 ansible_port=2602
k8_worker_2 ansible_host=127.0.0.1 ansible_port=2603
k8_worker_3 ansible_host=127.0.0.1 ansible_port=2604

[cluster:children]
control_nodes
worker_nodes
