k8-selinux-master
k8-selinux-node-1
k8-selinux-node-2
k8-selinux-node-3

[control_nodes]
k8-selinux-master

[worker_nodes]
k8-selinux-node-1
k8-selinux-node-2
k8-selinux-node-3

[cluster:children]
control_nodes
worker_nodes
