k8-ansible-master
k8-ansible-node-1
k8-ansible-node-2
k8-ansible-node-3


[control_nodes]
k8-ansible-master

[worker_nodes]
k8-ansible-node-1
k8-ansible-node-2
k8-ansible-node-3

[cluster:children]
control_nodes
worker_nodes
