#SPDX-License-Identifier: MIT-0
---
# tasks file for system_setup

# open vswitch is needed for networking purposes on the ubuntu 22.04 lts system
- include_tasks: openvswitch.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04" 

# disable dhcp
- name: Create static network interface
  ansible.builtin.template:
    src: netconf.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: '0600'

# errors here can be ignored. if the file is not there then it's already renamed
- name: Rename the current network interface file
  ansible.builtin.shell:
    cmd: mv 50-cloud-init.yaml 50-cloud-init.yaml.bk
    chdir: /etc/netplan
  ignore_errors: true

# disable cloud-init's network configuration
- name: disable cloud-init
  ansible.builtin.copy:
    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    content: "network: {config: disabled}"

# activate new interface file that sets a static IP address
- name: apply new netplan
  ansible.builtin.shell:
    cmd: netplan apply

# test that you can still ping the external IP for the machine
- name: test ping
  ansible.builtin.shell:
    cmd: ping -q -c5 {{ ansible_default_ipv4.address }}
  register: ping_test
  failed_when: '"5 packets transmitted, 5 received" not in ping_test.stdout'

# group of OS file config tasks that require system reboots
- include_tasks: os_config_tasks.yml

# install required packages
- name: Install a list of system packages
  ansible.builtin.apt:
    pkg:
    - software-properties-common 
    - curl

# check for key rings dir
- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

### Add the Kubernetes repository

# check apt source dir
- name: Ensure apt source directory exists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d
    state: directory
    mode: '0755'

# download k8 gpg keys
- name: Download and install Kubernetes apt keyring
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key |
    gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# add k8 repo location to package distribution list
- name: add k8 repo to package list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    create: true
    line: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /
    insertafter: EOF

### Add the CRI-O repository

# download CRI-O gpg keys
- name: Download and install CRI-O apt keyring
  ansible.builtin.shell: |
    curl -fsSL https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_version }}/deb/Release.key |
    gpg --batch --yes --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/cri-o-apt-keyring.gpg

# add CRI-O repo location to package distribution list
- name: add CRI-O repo to package list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/cri-o.list
    create: true
    line: deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_version }}/deb/ /
    insertafter: EOF

# run update and fix any broken packages
- name: fix any broken packages 
  ansible.builtin.apt:
    update_cache: yes
    dpkg_options: 'configure,all'
    state: fixed

# install CRI-O and K8 required packages
- name: Install a list of system packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
    - cri-o
    - kubelet
    - kubeadm
    - kubectl
    - acl

# Add main cni config location to CRI-O config
- name: Add cni network config file location
  ansible.builtin.blockinfile:
    path: /etc/crio/crio.conf.d/00-plugin-dir.conf
    create: true
    insertafter: EOF
    block: |
      [crio.network]
      plugin_dirs = [
        "/opt/cni/bin/",
      ]

# start and enable the crio-o service
- name: start the cri-o service
  ansible.builtin.systemd_service:
    name: crio.service
    enabled: true
    state: started

# start and enable the kubelet service
- name: start the kubelet service
  ansible.builtin.systemd_service:
    name: kubelet.service
    enabled: true
    state: started
