---

- name: setup k8 home directory
  hosts: control_nodes
  become: true
  become_user: root
  become_method: sudo
  vars:
    k8_user: banks
  tasks:
    # create the main configuration directory
    - name: create kube config directory
      ansible.builtin.file:
        path: "/home/{{ k8_user }}/.kube"
        state: directory
        owner: "{{ k8_user }}"
        group: "{{ k8_user }}"
        mode: '0755'

    # copy the main cluster config file
    - name: copy kube admin file to home directory
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf 
        dest: "/home/{{ k8_user }}/.kube/config"
        remote_src: true
        owner: "{{ k8_user }}"
        group: "{{ k8_user }}"
        mode: '0755'

    # at this point we can just setup the Weave network
    # https://github.com/weaveworks/weave/blob/master/site/kubernetes/kube-addon
    - name: install weave cni network
      become: true
      become_user: "{{ k8_user }}"
      ansible.builtin.shell: |
        cd $HOME
        kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
      register: weave_install

    # output weave debug
    - name: weave output debug
      ansible.builtin.debug:
        msg: "{{ weave_install.stdout }}"
